language: java
jdk:
  - openjdk8

branches:
  only:
    - master

before_install:
  - chmod +x gradlew

# Travis CI serverのホーム
  cache:
    directories:
      - '$HOME/.m2/repository'
      - '$HOME/.gralde'
script: "./gradlew clean build"

# CI 実行終了時　メールで　アラート
notifications:
  email:
    recipients:
      - enere6@gmail.com