language: java
jdk:
  - openjdk8

branches:
  only:
  - master

before_install:
  - chmod +x gradlew

# Travis CI 서버의 Home
cache:
  directories:
  - '$HOME/.m2/repository'
  - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy :
  - zip -r Freelec-springboot2-webservice2
  - mkdir -p deploy
  - mv Freelec-springboot2-webservice2.zip deploy/Freelec-springboot2-webservice2.zip

deploy :
  - provider: s3
  access_key_id: AKIAXP6FS33JRKRTNKHD
  secret_access_key: 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
  bucket: freelec-springboot-asemble-deploy
  region: ap-northeast-1
  skip_cleanup: true
  acl: private
  local_dir: deploy
  wait-until-deployed: true

# CI 실행 완료시 메일로 알람
notifications:
  email:
   recipients:
   - enere6@gmail.com