version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/step3/zip/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: stop.sh #NGINXと繋がっていないスプリンブートを終了
      timeout : 60
      runas : ec2-user
  ApplicationStart:
    - location: start.sh #NGINXと繋がっていないスプリンブートをstop.shで終了したもの'profile'で実行
      timeout: 60
      runas: ec2-user
  ValidateSerivce:
    - location: health.sh #新しいスプリブートが正常に実行されているか確認
      timeout: 60
      runas: ec-2user
